---
# This is my first playbook

# HEADER SECTION
 - name: This playbook will create a file
   hosts: webservers

# TASK SECTION
   tasks:

     - name: To install unzip
       apt:
         name: unzip
         state: absent

     - name: To create a folder using command module
       command: mkdir -p /opt/command
       args:
         creates: /opt/command
         chdir: /opt
